version: '3'

services:
  crawler:
    container_name: crawler
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - EXCHANGE_RATES_URL=${EXCHANGE_RATES_URL}
      - EXCHANGE_RATES_QUERYSTRING=${EXCHANGE_RATES_QUERYSTRING}
    build: .
    command: ./app
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine3.12
    env_file:
      - .env
    command: redis-server --requirepass ${DB_PASSWORD}
    restart: on-failure
    ports:
      - ${DB_PORT}:${DB_PORT}

        